version: "3"

services:
  mysql:
    build: "./mysql"
    ports:
      - "127.0.0.1:13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "verysecurerootpasswordiclassTECHtessolution12345672019docker"
      MYSQL_USER: mysql
      MYSQL_PASSWORD: "someothersecurepassword0123456"
  pma:
    image: "phpmyadmin/phpmyadmin:latest"
    ports:
      - "127.0.0.1:18080:80"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306
    depends_on:
      - mysql
